language: java
sudo: false
jdk:
  - oraclejdk8
deploy:
  provider: script
  script: ./.travis-deploy-snapshot.sh
  on:
  	branch: master
cache:
  directories:
  - $HOME/.gradle
  - $HOME/.m2
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c489689605a7c1ec7cb6
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
    - secure: Ywo0uOQSnPMDi1i5kjuJPHbZFwublWsIQmeHrpnKGAYp5SqC7euhf+FerEXnimDHIwqdHk8RG5Qc0A55wEjoOZOrtiOj4t1ziBlQ9HTOMcZkk5qUvvL5Kvw3Xfvc91FrxbT+YRp3enY+D9WzaS2IjeJvuZ39DfYoiIw1y5+EpS+NoYt2bmCjfvCi3l3j5ksyM2djt2WwaHGOZdtgJu/hbKOWyWt0ESWuM6dsaD1bOCsk8B0A+GDnVOZFv38Z2RtZpfQZe1SINr6ekHCuXhKjEGiHEQpKftWULB6vlUUsoVxFK9Lpx/ZwUUKoyYMqDHGdEyGQuNTsVzCe+t32PPypCJCbA8b7SJcRPXS6mRNHUP9QhfyRL4Pe3rSgf4+rra6qr9OwCNDwIM6VUFriWDPt/F5h9fLP/2Q48D2rH+/9nmFO1VMVH1WmJBLVK3cL1cs1eZXyQiU5Bw70WigKKvWkSAa9vzB6MMb8kRKjdeTOw/l2ZAwkO9F4S+JP9IcfwAbjbbGURCdeChN05mXHR6LjVcIVpy7dlB+TuRkcP2qX81MExKz4SMG+dbHeNBQ+DsTMC7jjJKx2DkKQUlCo0TPP8mdOJhgDuvLKd2BCjmAuJoCp9/3KwZGua728eci6yTyXVxMUIH441i5k9ZRsxNJwjvawkJ51bAF84z782PUx8Hc=
    - secure: AoBJI/aPHUnsy1nbx74Sq5AfUwy2hHkAOitfRhV5cZRYHKGVDf6YvF8Kz2GBU3a53ZSyZMSZgVBJWMGXCh5/YVLwVjXDuOKJuJjOKRgPx4c/ochj0qLYoTa1KgIwwQ8AlXXll3MW7yZ5o6YxsFC7RXFgQ4iEeyZrLCUAbHXm5ePVhhaAti1Cbq4euvJMJBifc0C2nhhir9xZ2bBWFtqX2Wp1eLe50zj3/OF988MdY8MJX12fzjpFp0jAtQTN7rs9synIv3pRJ4uGpr7v10IXwLwZtC56/LKm6I5J5sPQ+M3iH9zp7yXHuXlIbRPFK6IxczwAN4vthFGjcQv/8e/SLhbjGdimVTaHznM+aVL5PZSqO+gohzCX7XZM1jWXvrWmaP35YICAdqVoa9TwBRfbYIv3pPmdlyUK2IVm83dwZKHRJCQjxReOhCeaQe1h55P0SK70W8nOtIG06B1A3+TmugPmccSYcc6IoluO8a82I01ulBAW8ed+EWSmNvHil7i8wL0QIlZK6BhTa5Tl7Ji/FAR3ZMCJRIuv9hdDI79MKNPTvjZj7PmH7FP8HQOgewFMGzUThkT3H1UHtr7gRlTIWgxcj6yZ3QmouwsfkXNO7EblTVNqUwePoyT/hu1AGg0Aoz0a07/ftEErJADWtJwMAW2ljGmDnwAn+i5tpmZPkV0=
