language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c489689605a7c1ec7cb6
    on_success: change
    on_failure: always
    on_start: never
