title: Hawaii Framework
url: http://www.hawaiiframework.org

gems:
  - jekyll-sitemap

sass:
  style: :compressed

timezone: Europe/Amsterdam

github:
  url: https://github.com/hawaiifw/hawaii-framework

gitter:
  url: https://gitter.im/hawaiifw/hawaii-framework

google:
  analytics:
    tracking-id: UA-75184212-1

twitter:
  username: hawaiifw
  url: https://twitter.com/hawaiifw
