title: Hawaii Framework
url: http://www.hawaiiframework.org

gems:
  - jekyll-sitemap

sass:
  style: :compressed

timezone: Europe/Amsterdam

github:
  url: https://github.com/hawaiifw/hawaii-framework

twitter:
  username: hawaiifw
  url: https://twitter.com/hawaiifw
