title: Hawaii Framework
url: http://www.hawaiiframework.org

twitter:
  username: hawaiifw
  url: https://twitter.com/hawaiifw

gems:
  - jekyll-sitemap

sass:
  style: :compressed

timezone: Europe/Amsterdam
