spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    serialization:
      indent-output: false
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
logging:
  file: log/hawaii.log
  level:
    org.hawaiiframework: INFO
    org.springframework: INFO
hawaii:
  time:
    enabled: true
    timezone: UTC
  async:
    configuration: ./config/async-config.yml
  logging:
    frontend-ip-header-name: X-Hawaii-Frontend-IP-Address
    filters:
      kibana:
        enabled: true
      request-duration:
        enabled: true
      request-id:
        enabled: true
      request-response:
        enabled: true
        fallbackToFile: true
        directory: /tmp
        maxLogSize: 50k
        # For console logging, the allowed content types, empty means allow all.
        allowedContentTypes:
          - application/json
          - text/plain
          - text/xml
      transaction-id:
        enabled: true
      user-details:
        enabled: true

---

spring:
  profiles: dev
  jackson:
    serialization.indent-output: true
logging:
  level:
    org.hawaiiframework: DEBUG

---

spring:
  profiles: test

---

spring:
  profiles: prod
